### ISSUE TITLE
Question: XML?

### ISSUE THREAD

**Issue by cmsimike** [dguerri/LibVirtKvm-scripts#31]
Hi,

I am yet another happy user of your backup script. I did have a question about the backups. I presume this only backs up the disk image, right? Will we need another process to dump the domain's XML as part of a full backup? Or is that somehow in the image as well?

**Comment by dguerri** [comment]
Hi @cmsimike ! Thanks for the feedback and sorry for the delayed reply.
Did you find your answer? :)

**Comment by cmsimike** [comment]
No worries - I hadn't but I figured it was an answer I can eventually figure out. Slowly wrapping my head around libvirt :)

Another question I had -  is there a way to consolidate the backup directory?

**Comment by dguerri** [comment]
Cool. :)
About your question: it has been a while since I wrote the first version of this script.. as far as I remember consolidating needs a running domain. I don't know if something new has been implemented in  qemu-img, tho.
If not, you will need to restore the backup (or just creating a new domain which uses the latest backup image) and then consolidate using blockpull/blockcommit

**Comment by cmsimike** [comment]
Thank you very much!!
